### ISSUE TITLE
非常にいいソフトでありがとうございます！

### ISSUE THREAD

**Issue by T-Kuhn** [tarosay/IJKB#1]
家にIchigojamの出力を表示できるディスプレイがなくて、IJKBが非常に役に立ってます。
公開をありがとうございます。

ひとつ、気づいたこと：
```
10 X = 0
20 CLS
30 LOCATE X,24: PRINT "aa"
40 WAIT 30
41 LOCATE X,24: PRINT "  "
50 X = X + 1 
60 GOTO 30
70 END
```
みたいなプログラムを打つと、IJKBモニタの出力が少し予想外なものになります。出力バッファーの仕組みがチップ内装の仕組みと少し違う気がします。

**Comment by tarosay** [comment]
利用ありがとうございます。
　IJKBのメンテナンスを全然していないので、最近のIchigoJamに合わなくなっているところがたくさんあると思います。
　ソースを公開して誰でも修正できるようにしようかなと考えたりしたのですが、キーボード入力を内部で勝手に取得するプログラムコードなので、余り公開しない方がいいかなと思って、ソースを公開していませんでした。
　ただ、最近、IchigoJamをいじっていないので、済みませんがこのまま放置になってしまうと思います。

　そこで、思い切ってソースコードを公開したいと思います。
　forkして修正してくれる誰かに期待したいと思います。

**Comment by T-Kuhn** [comment]
早速のお返事をありがとうございます！
なるほど、そうだったんですね。
時間あったら見てみたいな、と思います。
このissueをクロースしますね。
